import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  innerContainer: { flexDirection: "row" },

  title: {},
  logo: {
    flex: 1,
    height: 150,
    width: "35%",
    alignSelf: "center",
    margin: 10,
  },
  rangeContainer: {
    flex: 1,
    alignItems: "center",
    marginBottom: 50,
  },
  slider: {
    width: width / 1.5,
    height: 10,
  },
  range: {
    marginBottom: 1,
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  password: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 2,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  confirmPass: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 2,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  firstname: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    maxWidth: width / 2.5,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 3,
    paddingLeft: 16,
  },
  lastname: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    maxWidth: width / 2.5,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 23,
    marginRight: 3,
    paddingLeft: 16,
  },
  button: {
    backgroundColor: "#E64398",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
  },
  Confirm: {
    flex: 1,
    alignItems: "center",
    marginBottom: 10,
  },
  footerText: {
    fontSize: 16,
    color: "#2e2e2d",
  },
  footerLink: {
    color: "#E64398",
    fontWeight: "bold",
    fontSize: 16,
  },
});
