import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#dceaff',
  },
  innerContainer: { flexDirection: 'row' },

  title: {},
  logo: {
    flex: 1,
    height: 150,
    width: '35%',
    alignSelf: 'center',
    margin: 10,
    marginTop: 35,
  },
  rangeContainer: {
    flex: 1,
    alignItems: 'center',
    padding: 25,
    marginBottom: 25,
  },
  responseContainer: { flex: 1, alignItems: 'center' },
  response: {
    fontSize: 11,
  },
  headingContainer: { flex: 1, alignItems: 'center' },
  heading: {
    fontSize: 16,
    color: '#929292',
  },
  slider: {
    width: width / 1.5,
    height: 1 / 2,
  },
  range: {
    marginBottom: 1,
  },
  end: { fontSize: 10, alignItems: 'center' },
  input: {
    height: 48,
    // borderRadius: 5,
    overflow: 'hidden',
    // backgroundColor: 'white',
    justifyContent: 'center',

    marginTop: 5,
    marginBottom: 5,
    marginLeft: 30,
    marginRight: 30,
    // paddingLeft: 10,
    // paddingRight: 10,
    // paddingBottom: 20,
  },

  firstname: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    // backgroundColor: 'white',
    maxWidth: width / 2.5,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 15,
    marginRight: 3,
    paddingLeft: 16,
  },
  lastname: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    //backgroundColor: 'white',
    maxWidth: width / 2.5,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 35,
    marginRight: 3,
    paddingLeft: 0,
  },
  button: {
    // backgroundColor: '#e64398',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggle: {
    backgroundColor: '#e64398',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 5,
    height: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  footerView: {
    flex: 1,
    alignItems: 'center',
    marginTop: 20,
  },
  Confirm: {
    flex: 1,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 16,
    color: '#2e2e2d',
  },
  footerLink: {
    color: '#E64398',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
