import { Dimensions, StyleSheet } from 'react-native';
const { width, height } = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    paddingTop: height / 8.25,
    flex: 1,
    justifyContent: 'center',
    height: height / 1.9,
    backgroundColor: '#dceaff',
  },
  innerContainer: { borderStyle: 'solid', borderWidth: 0 },
  title: { justifyContent: 'center' },
  logo: {
    flex: 1,
    height: 315,
    width: 350,

    alignSelf: 'center',
    margin: 10,
    marginLeft: 15,
    marginRight: 15,
  },
  text: {
    color: 'black',
    fontSize: 16,
  },
  input: {
    height: 70,
    // borderRadius: 5,
    overflow: 'hidden',
    // backgroundColor: 'white',
    justifyContent: 'center',

    paddingTop: 10,
    paddingBottom: 20,
    marginBottom: 10,
    paddingLeft: 30,
    paddingRight: 30,
    // width: width / 1.5,
    margin: 'auto',
    // paddingLeft: 10,
    // paddingRight: 10,
    // paddingBottom: 20,
  },
  inputContainer: {
    flex: 1,
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 30,
    paddingTop: 10,
    // paddingBottom: 20,
    borderColor: '#C5C5C5',
    backgroundColor: 'white',
    margin: 20,
    shadowOpacity: 0.2,
    shadowOffset: { width: 1, height: 5 },
  },
  registerContainer: {
    flex: 1,
    justifyContent: 'center',
    marginTop: 15,
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 30,
    borderColor: '#7E7E7E',
    paddingTop: 10,
    paddingBottom: 20,
    backgroundColor: '#DDDDDD',
    margin: 20,
  },

  button: {
    backgroundColor: '#E64398',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  register: {
    backgroundColor: '#B39BC8',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    height: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  footerView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginTop: 20,
  },
  footerText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#000000',
  },
  footerLink: {
    color: 'blue',
    fontWeight: 'normal',
    fontSize: 16,
  },
  generalError: {
    fontSize: 11,
    paddingBottom: 8 / 2,
    paddingTop: 8 / 2,
    textAlign: 'center',
    color: '#fc1f4a',
  },
});
